-- Generated by Stylix
local wezterm = require("wezterm")
wezterm.add_to_config_reload_watch_list(wezterm.config_dir)
local function stylix_wrapped_config()
    local wezterm = require 'wezterm'
local config = {}

config.front_end = "WebGpu"
config.enable_wayland = true

config.window_close_confirmation = 'NeverPrompt'

-- scrollbar
config.enable_scroll_bar = true

-- padding
config.window_padding = {
  left = 2,
  right = 0,
  top = 2,
  bottom = 0.
};

-- fancypants
config.window_background_opacity = 0.9;


-- tab bar
config.enable_tab_bar = true
config.hide_tab_bar_if_only_one_tab = false
config.use_fancy_tab_bar = false
config.tab_max_width = 25
config.show_tab_index_in_tab_bar = false
config.switch_to_last_active_tab_when_closing_tab = true

config.keys = {
  { key = "t", mods="SHIFT|CMD", action=wezterm.action.SpawnTab 'DefaultDomain' },
  { key = "d", mods="SHIFT|CMD", action=wezterm.action.CloseCurrentTab { confirm = true } }
}

return config

end
local stylix_base_config = wezterm.config_builder()
local stylix_user_config = stylix_wrapped_config()
stylix_base_config = {
    color_scheme = "stylix",
    font = wezterm.font_with_fallback {
        "Iosevka Comfy Wide",
        "Noto Color Emoji",
    },
    font_size = 15,
    window_background_opacity = 1.000000,
    window_frame = {
        active_titlebar_bg = "#665c54",
        active_titlebar_fg = "#d5c4a1",
        active_titlebar_border_bottom = "#665c54",
        border_left_color = "#3c3836",
        border_right_color = "#3c3836",
        border_bottom_color = "#3c3836",
        border_top_color = "#3c3836",
        button_bg = "#3c3836",
        button_fg = "#d5c4a1",
        button_hover_bg = "#d5c4a1",
        button_hover_fg = "#665c54",
        inactive_titlebar_bg = "#3c3836",
        inactive_titlebar_fg = "#d5c4a1",
        inactive_titlebar_border_bottom = "#665c54",
    },
    colors = {
      tab_bar = {
        background = "#3c3836",
        inactive_tab_edge = "#3c3836",
        active_tab = {
          bg_color = "#282828",
          fg_color = "#d5c4a1",
        },
        inactive_tab = {
          bg_color = "#665c54",
          fg_color = "#d5c4a1",
        },
        inactive_tab_hover = {
          bg_color = "#d5c4a1",
          fg_color = "#282828",
        },
        new_tab = {
          bg_color = "#665c54",
          fg_color = "#d5c4a1",
        },
        new_tab_hover = {
          bg_color = "#d5c4a1",
          fg_color = "#282828",
        },
      },
    },
    command_palette_bg_color = "#3c3836",
    command_palette_fg_color = "#d5c4a1",
    command_palette_font_size = 12,
}
for key, value in pairs(stylix_user_config) do
    stylix_base_config[key] = value
end
return stylix_base_config
