[colors]
ansi = ["#282828", "#fb4934", "#b8bb26", "#fabd2f", "#83a598", "#d3869b", "#8ec07c", "#d5c4a1"]
background = "#282828"
brights = ["#665c54", "#fb4934", "#b8bb26", "#fabd2f", "#83a598", "#d3869b", "#8ec07c", "#fbf1c7"]
compose_cursor = "#ebdbb2"
cursor_bg = "#d5c4a1"
cursor_fg = "#282828"
foreground = "#d5c4a1"
scrollbar_thumb = "#3c3836"
selection_bg = "#d5c4a1"
selection_fg = "#282828"
split = "#665c54"
visual_bell = "#fe8019"

[colors.tab_bar]
background = "#3c3836"
inactive_tab_edge = "#3c3836"
[colors.tab_bar.active_tab]
bg_color = "#282828"
fg_color = "#d5c4a1"

[colors.tab_bar.inactive_tab]
bg_color = "#665c54"
fg_color = "#d5c4a1"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#d5c4a1"
fg_color = "#282828"

[colors.tab_bar.new_tab]
bg_color = "#665c54"
fg_color = "#d5c4a1"

[colors.tab_bar.new_tab_hover]
bg_color = "#d5c4a1"
fg_color = "#282828"
